import { createRecovery, recoveryAction, recoverySteps } from '../src/domain/recovery';
/** Complete trusted test evidence, generated by the same ordered event model as gameplay. */
export function completedRecoveryEvidence() {
  let state = createRecovery();
  for (let phase = 0; phase < 3; phase++) {
    for (const step of recoverySteps(phase)) state = recoveryAction(state, { type: 'checkpoint', step: step.id });
    if (phase < 2) state = recoveryAction(state, { type: 'next' });
  }
  return state;
}
